services:
    judge-server:
        image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
        container_name: judge-server
        # restart: always
        read_only: false
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            # test_case 資料夾要掛後端專案裡面的
            # - ./data_dev/backend/test_case:/test_case:ro
            - /home/ipc/QDUOJ/OnlineJudge/data/test_case:/test_case:ro

            - ./data_dev/judge_server/log:/log
            - ./data_dev/judge_server/run:/judger
        environment:
            - SERVICE_URL=http://host.docker.internal:8080
            - BACKEND_URL=http://host.docker.internal:8000/api/judge_server_heartbeat/
            - TOKEN=SUPER1PC
            # - judger_debug=1
        # 只串 API，不用跟主機共享網路
        # network_mode: "host"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8000:8000"
            - "8080:8080"
