services:
    oj-redis:
        image: redis:4.0-alpine
        container_name: oj-redis
        # restart: always
        volumes:
            - ./data_dev/redis:/data
        ports:
            - "0.0.0.0:6380:6379"

    oj-postgres:
        image: postgres:10-alpine
        container_name: oj-postgres
        # restart: always
        volumes:
            - ./data_dev/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=onlinejudge
            - POSTGRES_USER=onlinejudge
            - POSTGRES_PASSWORD=onlinejudge
        ports:
            - "0.0.0.0:5435:5432"
